version: '3'

services:
  authbackend:
    depends_on:
      - db
    build:
      context: ./AuthBackend_TUTUIS
      dockerfile: Dockerfile
    container_name: AuthBackend
    restart: always
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      MAILGUN_USERNAME: ${MAILGUN_USERNAME}
      MAILGUN_PASSWORD: ${MAILGUN_PASSWORD}
      BASE_URL: ${BASE_URL}
    networks:
      - backend

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: tutuisdb
    ports:
      - "5432:5432"
    networks:
      - backend

  mailerbackend:
    build:
      context: ./MailerBackend_TUTUIS
      dockerfile: Dockerfile
    container_name: MailerBackend
    ports:
      - "3002:3002"
    restart: always
    networks:
      - backend

  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
    container_name: Dashboard
    restart: always
    networks:
      - frontend


  nginx:
    image: nginx:latest
    container_name: Nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Dashboard/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
    depends_on:
      - authbackend
      - mailerbackend
      - dashboard

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge