version: '3'

services:
  authbackend:
    depends_on:
      - db
    build:
      context: ./AuthBackend_TUTUIS
      dockerfile: Dockerfile
    container_name: AuthBackend
    image: horus19cdv/authbackend:latest
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      MAILGUN_USERNAME: ${MAILGUN_USERNAME}
      MAILGUN_PASSWORD: ${MAILGUN_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_REMITENTE: ${MAIL_REMITENTE}
      BASE_URL: ${BASE_URL}
      RABBIT_HOST: amqp://rabbitmq
    networks:
      - backend
  
  corebackend:
    depends_on:
      - db
    build:
      context: ./Core_TUTUIS
      dockerfile: Dockerfile
    container_name: CoreBackend
    image: horus19cdv/corebackend:latest
    restart: always
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      MAILGUN_USERNAME: ${MAILGUN_USERNAME}
      MAILGUN_PASSWORD: ${MAILGUN_PASSWORD}
      BASE_URL: ${BASE_URL}
    networks:
      - backend
    

  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: tutuisdb
    ports:
      - "5432:5432"
    networks:
      - backend

  mailerbackend:
    build:
      context: ./MailerBackend_TUTUIS
      dockerfile: Dockerfile
    container_name: MailerBackend
    image: horus19cdv/mailerbackend:latest
    environment:
      MAILGUN_USERNAME: ${MAILGUN_USERNAME}
      MAILGUN_PASSWORD: ${MAILGUN_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_REMITENTE: ${MAIL_REMITENTE}
    ports:
      - "3002:3002"
    restart: always
    networks:
      - backend

  socketbackend:
    build:
      context: ./Socket_Server_TUTUIS
      dockerfile: Dockerfile
    container_name: SocketBackend
    image: horus19cdv/socketbackend:latest
    environment:
      PORT: 3001
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      MAILGUN_USERNAME: ${MAILGUN_USERNAME}
      MAILGUN_PASSWORD: ${MAILGUN_PASSWORD}
      BASE_URL: ${BASE_URL}
    ports:
      - "3003:3003"
    restart: always
    networks:
      - backend

  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
    container_name: Dashboard
    image: horus19cdv/dashboard:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - frontend

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge